export const translateLanguages = [
  { key: "en", label: "English", icon: "/assets/flags/en-icon.png" },
  { key: "hi", label: "Hindi", icon: "/assets/flags/hi-icon.png" },
  { key: "pt", label: "Portuguese", icon: "/assets/flags/pt-icon.png" },
  { key: "zh", label: "Chinese", icon: "/assets/flags/zh-icon.png" },
  { key: "es", label: "Spanish", icon: "/assets/flags/es-icon.png" },
  { key: "fr", label: "French", icon: "/assets/flags/fr-icon.png" },
  { key: "de", label: "German", icon: "/assets/flags/de-icon.png" },
  { key: "ja", label: "Japanese", icon: "/assets/flags/ja-icon.png" },
  { key: "ar", label: "Arabic", icon: "/assets/flags/ar-icon.png" },
  { key: "ru", label: "Russian", icon: "/assets/flags/ru-icon.png" },
  { key: "ko", label: "Korean", icon: "/assets/flags/ko-icon.png" },
  { key: "id", label: "Indonesia", icon: "/assets/flags/id-icon.png" },
  { key: "it", label: "Italian", icon: "/assets/flags/it-icon.png" },
  { key: "nl", label: "Dutch", icon: "/assets/flags/nl-icon.png" },
  { key: "tr", label: "Turkish", icon: "/assets/flags/tr-icon.png" },
  { key: "pl", label: "Polish", icon: "/assets/flags/pl-icon.png" },
  { key: "sv", label: "Swedish", icon: "/assets/flags/sv-icon.png" },
  { key: "fil", label: "Filipino", icon: "/assets/flags/fil-icon.png" },
  { key: "ms", label: "Malay", icon: "/assets/flags/ms-icon.png" },
  { key: "ro", label: "Romanian", icon: "/assets/flags/ro-icon.png" },
  { key: "uk", label: "Ukrainian", icon: "/assets/flags/uk-icon.png" },
  { key: "el", label: "Greek", icon: "/assets/flags/el-icon.png" },
  { key: "cs", label: "Czech", icon: "/assets/flags/cs-icon.png" },
  { key: "da", label: "Danish", icon: "/assets/flags/da-icon.png" },
  { key: "fi", label: "Finnish", icon: "/assets/flags/fi-icon.png" },
  { key: "hr", label: "Croatian", icon: "/assets/flags/hr-icon.png" },
  { key: "sk", label: "Slovak", icon: "/assets/flags/sk-icon.png" },
  { key: "ta", label: "Tamil", icon: "/assets/flags/ta-icon.png" },
];

export const languages = [
  { key: "auto", label: "Autodetect" },
  { key: "en-US", label: "English" },
  { key: "id", label: "Indonesia" },
  { key: "ms", label: "Malay" },
  { key: "fil", label: "Filipino" },
  { key: "ko", label: "Korean" },
  { key: "ja", label: "Japanese" },
  { key: "zh", label: "Chinese" },
  { key: "es", label: "Spanish" },
  { key: "fr", label: "French" },
  { key: "de", label: "German" },
  { key: "it", label: "Italian" },
  { key: "pt", label: "Portuguese" },
  { key: "ar", label: "Arabic" },
  { key: "ru", label: "Russian" },
  { key: "nl", label: "Dutch" },
  { key: "tr", label: "Turkish" },
  { key: "pl", label: "Polish" },
  { key: "sv", label: "Swedish" },
  { key: "fi", label: "Finnish" },
  { key: "da", label: "Danish" },
  { key: "cs", label: "Czech" },
  { key: "hi", label: "Hindi" },
];