name: AWS Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18.20.0"
          cache: "npm"

      - name: Build project
        run: npm run build

      - name: Deploy to AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region eu-west-1
          aws s3 sync ./build s3://app.dubair.ai/
